# Generated by Django 2.2.2 on 2019-06-30 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190630_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='web.Session'),
        ),
    ]
